import { TicketPreset } from '../types';

export const PASS_PRESETS: TicketPreset[] = [
  {
    id: 'cinema-ticket',
    name: 'Retro Cinema Ticket',
    description: 'Vintage-themed movie admission ticket with tear-off coupon.',
    category: 'event',
    settings: {
      paperWidth: '80mm',
      fontVariant: 'retro-draft',
      dottedDividers: true,
      intensity: 4,
    },
    items: [
      { id: '1', type: 'header', text1: 'RETRO CINEMA CO.', align: 'center', bold: true, spacingAfter: 2 },
      { id: '2', type: 'subheader', text1: 'ADMIT ONE • MOVIE PASS', align: 'center', spacingAfter: 8 },
      { id: '3', type: 'dotted' },
      { id: '4', type: 'text', text1: 'FEATURE PRESENTATION', align: 'center', bold: true, size: 'sm', spacingAfter: 2 },
      { id: '5', type: 'header', text1: 'INTERSTELLAR', align: 'center', bold: true, doubleHeight: true, size: 'xl', spacingAfter: 4 },
      { id: '6', type: 'text', text1: '10TH ANNIVERSARY RE-RELEASE', align: 'center', bold: false, size: 'sm', spacingAfter: 12 },
      { id: '7', type: 'divider' },
      { id: '8', type: 'keyvalue', text1: 'DATE', text2: 'JUNE 15, 2026', spacingAfter: 4 },
      { id: '9', type: 'keyvalue', text1: 'TIME / SESSION', text2: '20:30 (8:30 PM)', spacingAfter: 4 },
      { id: '10', type: 'keyvalue', text1: 'THEATRE / SCREEN', text2: 'SCREEN 04 [IMAX]', spacingAfter: 4 },
      { id: '11', type: 'keyvalue', text1: 'ROW / SEAT', text2: 'ROW K - SEAT 18', bold: true, spacingAfter: 4 },
      { id: '12', type: 'keyvalue', text1: 'PRICE / TYPE', text2: '$14.50 [ADULT]', spacingAfter: 12 },
      { id: '13', type: 'divider' },
      { id: '14', type: 'text', text1: 'SCAN QR FOR DIGITAL RECEIPT & SNACKS', align: 'center', size: 'sm', spacingAfter: 8 },
      { id: '15', type: 'qrcode', value: 'https://retro-cinema.example.com/ticket/98375', align: 'center', spacingAfter: 12 },
      { id: '16', type: 'dotted' },
      { id: '17', type: 'text', text1: '[ TEAR ALONG DOTTED LINE ]', align: 'center', size: 'sm', spacingAfter: 8 },
      { id: '18', type: 'text', text1: 'STUB - MOVIE TICKETS', align: 'center', bold: true, size: 'md', spacingAfter: 2 },
      { id: '19', type: 'text', text1: 'TICKET #9837512 - SECURE ENTRY', align: 'center', size: 'sm', spacingAfter: 8 },
      { id: '20', type: 'barcode', value: 'CIN9837512', align: 'center', spacingAfter: 4 }
    ]
  },
  {
    id: 'boarding-pass',
    name: 'Airline Boarding Pass',
    description: 'Clean high-density transit coupon matching authentic boarding cards.',
    category: 'transit',
    settings: {
      paperWidth: '80mm',
      fontVariant: 'clean-mono',
      dottedDividers: false,
      intensity: 3,
    },
    items: [
      { id: '1', type: 'header', text1: 'SKYLINE AIRWAYS', align: 'center', bold: true, spacingAfter: 2 },
      { id: '2', type: 'text', text1: 'BOARDING PASS • CONFIRMED', align: 'center', size: 'sm', spacingAfter: 8 },
      { id: '3', type: 'divider' },
      { id: '4', type: 'columns', text1: 'FLIGHT', text2: 'GATE', text3: 'SEAT', bold: true, spacingAfter: 2 },
      { id: '5', type: 'columns', text1: 'SA-942', text2: 'B-14', text3: '12F', spacingAfter: 12 },
      { id: '6', type: 'columns', text1: 'DEPART', text2: 'BOARD TIME', text3: 'ZONE', bold: true, spacingAfter: 2 },
      { id: '7', type: 'columns', text1: '14:20', text2: '13:40', text3: 'GRP 2', spacingAfter: 12 },
      { id: '8', type: 'divider' },
      { id: '9', type: 'keyvalue', text1: 'FROM:', text2: 'LONDON LHR (LHR)', spacingAfter: 4 },
      { id: '10', type: 'keyvalue', text1: 'TO:', text2: 'TOKYO HANEDA (HND)', spacingAfter: 4 },
      { id: '11', type: 'keyvalue', text1: 'PASSENGER:', text2: 'BOSLEY / JAY MR', spacingAfter: 12 },
      { id: '12', type: 'text', text1: 'IMPORTANT: GATES CLOSE 15M BEFORE DEPART', align: 'left', size: 'sm', spacingAfter: 6 },
      { id: '13', type: 'text', text1: 'CARRY-ON: 1 PERSONAL ITEM, 1 CABIN BAG', align: 'left', size: 'sm', spacingAfter: 12 },
      { id: '14', type: 'barcode', value: 'LHRSAT12FBOS', align: 'center', spacingAfter: 12 },
      { id: '15', type: 'text', text1: 'Thank you for flying Skyline!', align: 'center', size: 'sm' }
    ]
  },
  {
    id: 'cafe-receipt',
    name: 'Artisan Coffee Receipt',
    description: 'A delicate coffee shop checkout voucher with customized columns and Wi-Fi code.',
    category: 'retail',
    settings: {
      paperWidth: '58mm',
      fontVariant: 'vintage-serif',
      dottedDividers: true,
      intensity: 5,
    },
    items: [
      { id: '1', type: 'header', text1: 'OAK & BEAN', align: 'center', bold: true, spacingAfter: 2 },
      { id: '2', type: 'text', text1: '42 Broad Street, Oxford', align: 'center', size: 'sm', spacingAfter: 8 },
      { id: '3', type: 'keyvalue', text1: 'Cashier:', text2: 'Sarah M.', spacingAfter: 2 },
      { id: '4', type: 'keyvalue', text1: 'Date:', text2: 'Jun 04, 2026 10:45 AM', spacingAfter: 8 },
      { id: '5', type: 'dotted' },
      { id: '6', type: 'columns', text1: 'QTY / ITEM', text2: '', text3: 'PRICE', bold: true, spacingAfter: 4 },
      { id: '7', type: 'columns', text1: '1 x Flat White (Double)', text2: '', text3: '£3.80', spacingAfter: 2 },
      { id: '8', type: 'columns', text1: '1 x Almond Croissant', text2: '', text3: '£3.20', spacingAfter: 2 },
      { id: '9', type: 'columns', text1: '1 x Cold Brew (Venti)', text2: '', text3: '£4.20', spacingAfter: 8 },
      { id: '10', type: 'dotted' },
      { id: '11', type: 'keyvalue', text1: 'SUBTOTAL', text2: '£11.20', spacingAfter: 2 },
      { id: '12', type: 'keyvalue', text1: 'TAX (VAT 20%)', text2: '£2.24', spacingAfter: 4 },
      { id: '13', type: 'keyvalue', text1: 'TOTAL', text2: '£11.20', bold: true, spacingAfter: 12 },
      { id: '14', type: 'text', text1: 'FREE GUEST WI-FI CODE:', align: 'center', bold: true, size: 'sm', spacingAfter: 2 },
      { id: '15', type: 'text', text1: 'COFFEE-AND-OAK-9921', align: 'center', bold: true, spacingAfter: 8 },
      { id: '16', type: 'qrcode', value: 'WIFI:S:OakAndBean_Guest;T:WPA;P:oakbean2026;;', align: 'center', spacingAfter: 12 },
      { id: '17', type: 'text', text1: 'THANK YOU! JOIN OUR CLUB', align: 'center', size: 'sm', spacingAfter: 8 },
      { id: '18', type: 'barcode', value: 'TX10459921', align: 'center' }
    ]
  },
  {
    id: 'parking-ticket',
    name: 'Downtown Parking Slip',
    description: 'High-contrast parking slip with entry details, rate info, and barcode.',
    category: 'utility',
    settings: {
      paperWidth: '58mm',
      fontVariant: 'retro-draft',
      dottedDividers: false,
      intensity: 5,
    },
    items: [
      { id: '1', type: 'header', text1: 'CITY COMMERCE PARK', align: 'center', bold: true, spacingAfter: 2 },
      { id: '2', type: 'subheader', text1: 'METROPOLITAN PARKING', align: 'center', spacingAfter: 8 },
      { id: '3', type: 'divider' },
      { id: '4', type: 'text', text1: 'ENTRY TICKET - PLEASE KEEP IN CAR', align: 'center', bold: true, size: 'sm', spacingAfter: 12 },
      { id: '5', type: 'keyvalue', text1: 'LOT STATION', text2: 'EAST LANE B', spacingAfter: 4 },
      { id: '6', type: 'keyvalue', text1: 'DATE', text2: '04/06/2026', spacingAfter: 4 },
      { id: '7', type: 'keyvalue', text1: 'ENTRY TIME', text2: '17:38:29', bold: true, spacingAfter: 12 },
      { id: '8', type: 'divider' },
      { id: '9', type: 'text', text1: 'PARKING RATES:', align: 'left', bold: true, size: 'sm', spacingAfter: 4 },
      { id: '10', type: 'keyvalue', text1: 'First 30 Mins', text2: 'FREE', spacingAfter: 2 },
      { id: '11', type: 'keyvalue', text1: '1 to 2 Hours', text2: '$5.00', spacingAfter: 2 },
      { id: '12', type: 'keyvalue', text1: 'Daily Max', text2: '$24.00', spacingAfter: 12 },
      { id: '13', type: 'barcode', value: 'PKG202606041738', align: 'center', spacingAfter: 12 },
      { id: '14', type: 'text', text1: 'Scan barcode at pay machine on exit', align: 'center', size: 'sm' }
    ]
  },
  {
    id: 'museum-badge',
    name: 'Vintage Museum Entry',
    description: 'Elegant admission pass with clean serif style, ticketing code and MoM info.',
    category: 'event',
    settings: {
      paperWidth: '80mm',
      fontVariant: 'vintage-serif',
      dottedDividers: true,
      intensity: 4,
    },
    items: [
      { id: '1', type: 'header', text1: 'MUSEUM OF NEW ART', align: 'center', bold: true, spacingAfter: 4 },
      { id: '2', type: 'text', text1: 'DAILY GENERAL ADMISSION', align: 'center', size: 'sm', bold: true, spacingAfter: 8 },
      { id: '3', type: 'dotted' },
      { id: '4', type: 'text', text1: 'VALID ONLY ON DATE OF ISSUE', align: 'center', size: 'sm', spacingAfter: 8 },
      { id: '5', type: 'keyvalue', text1: 'VISITOR TYPE:', text2: 'EXHIBIT MEMBER', bold: true, spacingAfter: 4 },
      { id: '6', type: 'keyvalue', text1: 'TICKET CODE:', text2: 'MNA-77291-B', spacingAfter: 4 },
      { id: '7', type: 'keyvalue', text1: 'ISSUED BY:', text2: 'E-KIOSK 02', spacingAfter: 4 },
      { id: '8', type: 'keyvalue', text1: 'ADMIT COUNT:', text2: '1 SINGLE ADULT', spacingAfter: 12 },
      { id: '9', type: 'dotted' },
      { id: '10', type: 'text', text1: 'SCAN AT ROTUNDA GATEWAYS', align: 'center', size: 'sm', spacingAfter: 8 },
      { id: '11', type: 'qrcode', value: 'MNA-GATE-77291', align: 'center', spacingAfter: 12 },
      { id: '12', type: 'text', text1: '★ THANK YOU FOR SUPPORTING THE MoM ★', align: 'center', size: 'sm' }
    ]
  },
  {
    id: 'golf-course-pass',
    name: 'Pebble Creek Golf Club',
    description: 'Greens certificate, tee-off reservation details & scorecard linkage.',
    category: 'utility',
    settings: {
      paperWidth: '80mm',
      fontVariant: 'vintage-serif',
      dottedDividers: true,
      intensity: 4,
    },
    items: [
      { id: 'g1', type: 'header', text1: 'PEBBLE CREEK GOLF', align: 'center', bold: true, spacingAfter: 2 },
      { id: 'g2', type: 'subheader', text1: 'PLAYER ACCESS CONFIRMED', align: 'center', spacingAfter: 8 },
      { id: 'g3', type: 'dotted' },
      { id: 'g4', type: 'keyvalue', text1: 'PLAYER NAME', text2: 'JAY BHOSLAY', bold: true, spacingAfter: 4 },
      { id: 'g5', type: 'keyvalue', text1: 'START TEE TIME', text2: '08:15 AM (HOLE 01)', spacingAfter: 4 },
      { id: 'g6', type: 'keyvalue', text1: 'GOLF CART ACCESS', text2: 'CART-42 (INCLUDED)', spacingAfter: 4 },
      { id: 'g7', type: 'keyvalue', text1: 'GREENS TYPE', text2: '18-HOLE PREMIUM CHAMP', spacingAfter: 8 },
      { id: 'g8', type: 'divider' },
      { id: 'g9', type: 'columns', text1: 'HOLE', text2: 'PAR', text3: 'DISTANCE', bold: true, spacingAfter: 2 },
      { id: 'g10', type: 'columns', text1: 'HOLE 01', text2: '04', text3: '380 YDS', spacingAfter: 2 },
      { id: 'g11', type: 'columns', text1: 'HOLE 02', text2: '05', text3: '520 YDS', spacingAfter: 2 },
      { id: 'g12', type: 'columns', text1: 'HOLE 03', text2: '03', text3: '145 YDS', spacingAfter: 12 },
      { id: 'g13', type: 'dotted' },
      { id: 'g14', type: 'text', text1: 'SCAN QR CODE FOR OVERALL LEADERBOARD', align: 'center', size: 'sm', spacingAfter: 8 },
      { id: 'g15', type: 'qrcode', value: 'https://pebblecreekgolf.example.com/live/score', align: 'center', spacingAfter: 12 },
      { id: 'g16', type: 'text', text1: '[ TEAR ALONG CUTLINE ]', align: 'center', size: 'sm', spacingAfter: 8 },
      { id: 'g17', type: 'text', text1: 'CLUB HOUSE VOUCHER - CART RETURN', align: 'center', bold: true, size: 'sm', spacingAfter: 4 },
      { id: 'g18', type: 'barcode', value: 'CARTCODE42', align: 'center' }
    ]
  },
  {
    id: 'concert-ticket',
    name: 'Concert Night Music Pass',
    description: 'High-contrast rock show arena admission pass with serial barcoding.',
    category: 'event',
    settings: {
      paperWidth: '80mm',
      fontVariant: 'retro-draft',
      dottedDividers: false,
      intensity: 5,
    },
    items: [
      { id: 'c1', type: 'header', text1: 'STADIUM CLUB LIVE', align: 'center', bold: true, spacingAfter: 2 },
      { id: 'c2', type: 'subheader', text1: 'CONCERT ACCESS TICKET', align: 'center', spacingAfter: 12 },
      { id: 'c3', type: 'text', text1: 'THE ELECTRIC PYRE TOUR', align: 'center', bold: true, size: 'xl', spacingAfter: 4 },
      { id: 'c4', type: 'text', text1: 'LIVE IN CONCERT NIGHT', align: 'center', size: 'md', spacingAfter: 12 },
      { id: 'c5', type: 'divider' },
      { id: 'c6', type: 'keyvalue', text1: 'DOORS OPEN', text2: '19:00 (7:00 PM)', spacingAfter: 4 },
      { id: 'c7', type: 'keyvalue', text1: 'SHOWTIME STARTS', text2: '20:15 (8:15 PM)', spacingAfter: 4 },
      { id: 'c8', type: 'keyvalue', text1: 'ZONE STAGE', text2: 'GENERAL STANDING [FRONT]', bold: true, spacingAfter: 4 },
      { id: 'c9', type: 'keyvalue', text1: 'ORDER REF', text2: 'TX-ELECTRIC-9922', spacingAfter: 12 },
      { id: 'c10', type: 'dotted' },
      { id: 'c11', type: 'text', text1: 'No professional recording devices allowed.', align: 'center', size: 'sm', spacingAfter: 2 },
      { id: 'c12', type: 'text', text1: 'Exchange this voucher for a wristband at door.', align: 'center', size: 'sm', spacingAfter: 12 },
      { id: 'c13', type: 'barcode', value: 'CON9912049281', align: 'center', spacingAfter: 6 }
    ]
  }
];
